### ISSUE TITLE
PC docs

### ISSUE THREAD

**Issue by VovanR** [VovanR/onair#4]
Webcamera is active (1 or 0 when inactive):
```shell
lsmod | grep uvcvideo --max-count=1 | awk '{print $3}'
```

Check every 5 seconds.  
With systemd https://wiki.archlinux.org/title/Systemd/User    
```shell
mkdir -p ~/.config/systemd/user/
```

`touch ~/.config/systemd/user/onair.service`
```
[Unit]
Description=Onair Daemon

[Service]
ExecStart=%h/.local/bin/onair.sh

[Install]
WantedBy=default.target
```

`touch .config/systemd/user/onair.timer`
```
[Unit]
Description=Onair Schedule

[Timer]
AccuracySec=1s
OnBootSec=5
OnUnitActiveSec=5

[Install]
WantedBy=timers.target
```

after edit reload
```shell
systemctl --user daemon-reload 
```

Check
```shell
systemctl --user
journalctl --user-unit onair.service
systemctl --user status onair.service
```

```shell
mkdir ~/.local/bin/
touch ~/.local/bin/onair.sh
```

```bash
#!/bin/bash

fn () {
	status=$(lsmod | grep uvcvideo --max-count=1 | awk '{print $3}')
	if [ ${status} == "1" ]; then
		curl -d '{"status":true}' -X POST http://192.168.1.1:3000/api/status -H "Content-Type: application/json" 
	fi
}

fn

exit 0
```

systemctl --user enable onair.service
systemctl --user start onair.service
systemctl --user enable onair.timer
systemctl --user start onair.timer

**Comment by VovanR** [comment]
Podman

```shell
podman kube play onair.yaml
```

**Comment by VovanR** [comment]
Build container
```shell
podman build -t onair-app:latest .
```
Run
```shell
podman run -p 3000:3000 --rm --detach onair-app:latest
```
or
```shell
podman play kube onair.yaml
```
`onair.yaml`
```yaml
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.2.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-09-29T10:11:51Z"
  labels:
    app: onair-pod
  name: onair-pod
spec:
  containers:
  - args:
    - npm
    - start
    image: localhost/onair-app:latest
    name: onair-app
    ports:
    - containerPort: 3000
      hostPort: 3000
```
